start_pod1:
	kubectl create -f ember-app-pod.yaml
start_pod2:
	kubectl create -f ember-app-pod2.yaml
start_service:
	kubectl create -f ember-app-service.yaml
get_pod:
	kubectl get pods -l app=ember-app
get_service:
	kubectl get service ember-app-service
