start_metrics:
	kubectl apply -f 1.8+
get_apiservices:
	kubectl get apiservices
create_name_space:
	kubectl create namespace mem-example
create_pod:
	kubectl apply -f memory-request-limit.yaml --namespace=mem-example



